FROM golang:1.25-alpine

RUN apk add --no-cache git gcc musl-dev

WORKDIR /app

# Pre-download dependencies to speed up container start
COPY go.mod go.sum ./
RUN go mod download

# Entrypoint will be overridden by compose to allow source mounting
ENTRYPOINT ["sh", "-c", "go build -o /usr/local/bin/ntlc cmd/ntlc/main.go && go run cmd/nautilus-core/main.go --ntlc /usr/local/bin/ntlc"]
